name: DevSecOps Pipeline

on:
  workflow_dispatch:
  push:
    paths:
      - Dockerfile
      - "app/**"
      - "k8s/**"
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Check Python
        run: |
          which python3
          python3 --version

      - name: SAST - Semgrep
        run: |
          python3 -m pip install --user semgrep
          python3 -m semgrep scan --config auto || true

      - name: Build Docker image
        run: docker build -t vulnerable-app:latest .

      - name: SCA - Trivy Image Scan
        run: |
          docker run --rm \
            -v /var/run/docker.sock:/var/run/docker.sock \
            ghcr.io/aquasecurity/trivy:0.50.1 image \
            --exit-code 0 \
            --severity HIGH,CRITICAL \
            vulnerable-app:latest

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Prepare ZAP report directory
        run: |
          mkdir -p /tmp/zap_reports
          chmod 777 /tmp/zap_reports
          kubectl port-forward svc/vulnerable-app 9090:80 &
          sleep 10
          curl -f http://127.0.0.1:9090 || (echo "Service is NOT running"; exit 1)
          echo "Service is up and running"

      - name: DAST - ZAP Baseline Scan
        run: |
          docker run --rm \
            --network host \
            -v /tmp/zap_reports:/zap/wrk \
            ghcr.io/zaproxy/zaproxy:2.15.0 \
            zap-baseline.py \
              -t http://127.0.0.1:9090 \
              -w /zap/wrk/report.md \
              -m 1 \
              -I \
              --autooff \
              -T 3 || true

      - name: ZAP report
        run: |
          ls -la /tmp/zap_reports/ || echo "No files"
          echo "Report saved"

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-security-report
          path: /tmp/zap_reports/

      - name: Show ZAP report
        run: |
          cat /tmp/zap_reports/report.md || echo "No MD report"
